
//Create a new variable for don't repeat codigo
@apí = http://localhost:4000/servicios

###List of services
GET {{apí}}

###List of services por id
GET {{apí}}/4

###Eliminacion por id
DELETE {{apí}}/8


###Insert new servicie
POST {{apí}}
Content-Type: application/json

{
    "nombre": "Medimas"
}

###

PUT {{apí}}/6
Content-Type:  application/json

{
    "nombre":"otro gasto"

}
